# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=7436
@group=tt

@league=Reading
@season=Senior_2021-22
@team=Our%20Lady%20Of%20Peace%20A


###

GET https://{{hostname}}:{{port}}/Calendar/{{league}}/{{team}}?command=json

###

GET https://{{hostname}}:{{port}}/Calendar/{{league}}/{{team}}

###



GET https://{{hostname}}:{{port}}/{{group}}/fixtures/{{league}}

###

GET https://{{hostname}}:{{port}}/{{group}}/fixtures/{{league}}/{{team}}

###


GET https://{{hostname}}:{{port}}/{{group}}/fixtures/Senior_2021-22/{{league}}/{{team}}

###

# Get the Team from a particular season
GET https://{{hostname}}:{{port}}/{{group}}/team/{{season}}/{{league}}/{{team}}

###


# Get the players from a team
GET https://{{hostname}}:{{port}}/{{group}}/teamplayers/{{league}}/{{team}}

###

# Get the players from a team in a particular season
GET https://{{hostname}}:{{port}}/{{group}}/teamplayers/{{season}}/{{league}}/{{team}}

###


# Get the players from a team in a particular season
GET https://{{hostname}}:{{port}}/{{group}}/teamplayers/2019/{{league}}/{{team}}

###

