namespace Smab.TTInfo.TTLeagues.Models;

public record Competition(
	int Id,
	int LeagueId,
	string Name,
	string MenuName,
	object StartDate,
	object StartTime,
	string UserId,
	object FormatId,
	object GamesPerSet,
	string Description,
	string Details,
	object PointId,
	object MinAge,
	object MaxAge,
	string OrganiserId,
	object Organiser,
	object MatchCard,
	object Table,
	object Averages,
	object Reserves,
	object GameFormat,
	object EndDate,
	int PlayEachOther,
	bool PlayAll,
	object Ready,
	object Deleted,
	object Published,
	object Archived,
	object Hidden,
	int FixtureFormat,
	int ResultDisplay,
	string League,
	object Night,
	bool ManualScoring,
	bool Ranking,
	object TableCount,
	object Days,
	object SubmissionPeriods,
	bool SplitRounds,
	int CaptainType,
	int PlayerType,
	object GroupId,
	object Group,
	int GroupOrdering,
	bool HalfGeneration,
	bool AdvancedOptions,
	bool TableAllocation,
	bool ShowReserves,
	bool RequirePlayers,
	bool RankOrder,
	object AgeEligibility,
	object MembershipEligibility,
	object GenderEligibility,
	object RegistrationCompetitionType,
	object RegistrationId,
	bool RankingSubmission,
	bool DoublesPOTM,
	bool FastFormat,
	bool ExportNationalRankings,
	string NationalRankingCategory,
	int PrintoutFormat,
	bool TeamHandicap
)
{
	// Added manually - not part of API call
	public List<Division> Divisions { get; set; } = [];
}

