namespace Smab.TTInfo.TTLeagues.Models.TTLeagues;

public sealed record Match(
	int Id,
	MatchTeamInfo Home,
	MatchTeamInfo Away,
	DateTimeOffset? Date,
	DateTimeOffset? Time,
	int? Week,
	string Name,
	string Venue,
	int? GroupingId,
	int CompetitionId,
	int DivisionId,
	long? PreviousLinkId,
	DateTimeOffset? Submitted,
	DateTimeOffset? Approved,
	DateTimeOffset? Rejected,
	DateTimeOffset? Overridden,
	Person? SubmittedBy,
	Person? ApprovedBy,
	Person? RejectedBy,
	Person? OverriddenBy,
	int? VenueId,
	DateTimeOffset? Forfeit,
	string ForfeitReason,
	int? ForfeitId,
	string AbandonedReason,
	DateTimeOffset? Abandoned,
	int LeagueId,
	int? ClubId,
	int? CountyId,
	string Competition,
	DateTimeOffset Updated,
	bool Manual,
	DateTimeOffset? Published,
	DateTimeOffset? Archived,
	Person? Potm,
	int? PotmType,
	int Entry,
	bool HasReport,
	bool HasComments,
	int ResultDisplay,
	bool PlayAll,
	bool HasResults,
	int ScoreUp,
	object? Round,
	object? TableNo,
	object? DayId,
	ImmutableList<PlayerScore> HomeScores,
	ImmutableList<PlayerScore> AwayScores,
	string HomeName,
	string AwayName,
	object? Number,
	object? Stage,
	object? RoundModel,
	object? HomeHandicap,
	object? AwayHandicap,
	object? Bye
)
{
	/// <summary>
	/// Gets the combined date and time value based on the <see cref="Date"/> and <see cref="Time"/> properties.
	/// </summary>
	public DateTimeOffset? ActualDateTime => Date?.Date.AddHours(Time?.Hour ?? 0).AddMinutes(Time?.Minute ?? 0);
};
