name: Build and deploy .NET Core app to Windows WebApp TTInfo
on:
  push:
    branches:
    - main

  # Allow manual workflow
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: TTInfo
  AZURE_WEBAPP_PACKAGE_PATH: src\Smab.TTInfo.Server\publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.TTInfo_21ee }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.100
  WORKING_DIRECTORY: src\Smab.TTInfo.Server
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
